# Generated by Django 3.0.3 on 2020-04-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200413_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='status',
            field=models.CharField(choices=[('Available', 'available'), ('Returned', 'returned')], default='Available', max_length=255),
        ),
    ]
