# Generated by Django 3.0.3 on 2020-04-21 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200421_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_movie',
            old_name='user_id',
            new_name='user',
        ),
    ]
