# Generated by Django 3.0.3 on 2020-04-21 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200421_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_movie',
            name='insert_date',
        ),
        migrations.AddField(
            model_name='user_movie',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
