# Generated by Django 3.0.3 on 2020-04-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200421_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default='2020-04-22 12:38:50', editable=False),
        ),
    ]
