# Generated by Django 3.0.3 on 2020-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200422_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default='2020-04-22 12:48:23', editable=False),
        ),
        migrations.AlterField(
            model_name='user_movie',
            name='price',
            field=models.FloatField(default=1, editable=False),
        ),
    ]
