# Generated by Django 3.0.3 on 2020-04-22 12:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200422_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 13, 2, 26, 760749), editable=False),
        ),
    ]
