# Generated by Django 3.0.3 on 2020-04-22 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200422_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 12, 13, 51, 172081, tzinfo=utc), editable=False),
        ),
    ]
