# Generated by Django 3.0.3 on 2020-04-22 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200422_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 13, 14, 38, 387267), editable=False),
        ),
    ]
