# Generated by Django 3.0.3 on 2020-04-22 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200422_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='insert_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
