# Generated by Django 3.0.3 on 2020-04-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200422_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='price',
            field=models.FloatField(editable=False),
        ),
    ]
