# Generated by Django 3.0.3 on 2020-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200422_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie',
            name='price',
            field=models.FloatField(editable=False, null=None),
        ),
    ]
